id = "blueprint"
name = "Blueprint"
version = "0.2.0"
schema_version = 1
authors = ["tfuxu <tfuxu@tutanota.com>"]
description = "Language support for Blueprint (.blp) files"
repository = "https://github.com/tfuxu/zed-blueprint"

[grammars.blueprint]
repository = "https://github.com/smrtrfszm/tree-sitter-blueprint"
commit = "b3a05548b37cf28bb901a2a3a07e7bfe6b299f73"

[language_servers.blueprint]
name = "Blueprint Language Server"
language = "Blueprint"
